### PR TITLE
Move to v0.9.1

### PR DESCRIPTION
**Pull request by manuelbuil**
Merge v0.9.1 of the containernetworking/plugins project and add on top our patches:
* https://github.com/rancher/plugins/commit/6ad65a095ddfdb5b30ae61f7acd183b80b738410 (creates cni binary for k3s)
* https://github.com/rancher/plugins/commit/92fe4dd41c0b663624fe578b06e09b81c6e81173 (updates vendor)
* https://github.com/rancher/plugins/commit/8521f9fe61cca42348ae1c3f61f8986a2864697d (removes part of the tests)

This is needed for k3s dual-stack feature

### CODE REVIEW

**Comment by manuelbuil** [comment]
When adding this into k3s (on top of my PR updating flanneld), I was able to see two IPs in my pod on k3s:

```
ubuntu@ip-10-0-10-7:~/k3s$ k exec -ti multitool-deployment-79d98599fb-sjq7p ip a
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0@if155: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 8951 qdisc noqueue state UP group default 
    **link/ether 96:a3:75:5b:34:20 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.42.0.9/24 brd 10.42.0.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2001:cafe:42::9/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::94a3:75ff:fe5b:3420/64 scope link 
       valid_lft forever preferred_lft forever**
```

**Review by vadorovsky — COMMENTED** [review]
What's the reason behind 8521f9f? These are just some Golang tests which should run fine on Github Actions. Is there any particular problem with having them enabled in this fork?

**Comment by vadorovsky** [comment]
Also, is 6ad65a0 being upstreamed in the meantime?

**Comment by manuelbuil** [comment]
> Also, is [6ad65a0](https://github.com/rancher/plugins/commit/6ad65a095ddfdb5b30ae61f7acd183b80b738410) being upstreamed in the meantime?

This is something specific of k3s. Instead of having the different binaries separately (bridge, flannel, vlan...), this commit creates one single binary called cni which contains all the cni plugins (imported as libraries)

**Comment by manuelbuil** [comment]
> What's the reason behind [8521f9f](https://github.com/rancher/plugins/commit/8521f9fe61cca42348ae1c3f61f8986a2864697d)? These are just some Golang tests which should run fine on Github Actions. Is there any particular problem with having them enabled in this fork?

Because the resulting binary (cni) is not what tests are expecting

**Review by vadorovsky — APPROVED** [review]
Thanks for explanation!

**Review by dweomer — APPROVED** [review]

**Pull request merged**
